<?php
/**
 * Copyright © Grupo Sonet360 S.A. de C.V. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $_parametros = $_SESSION['banorte_parametros_3dsecure']; ?>
<form name="payworks_3dsecure" method="post" action="https://via.banorte.com/secure3d/Solucion3DSecure.htm">
	<input type="hidden" name="CARD_NUMBER" value="<?php echo $_parametros['CARD_NUMBER']; ?>">
	<input type="hidden" name="CARD_EXP" value="<?php echo $_parametros['CARD_EXP']; ?>">
	<input type="hidden" name="AMOUNT" value="<?php echo $_parametros['AMOUNT']; ?>">
	<input type="hidden" name="CARD_TYPE" value="<?php echo $_parametros['CARD_TYPE']; ?>">
	<input type="hidden" name="MERCHANT_ID" value="<?php echo $_parametros['MERCHANT_ID']; ?>">
	<input type="hidden" name="MERCHANT_NAME" value="<?php echo $_parametros['MERCHANT_NAME']; ?>">
	<input type="hidden" name="MERCHANT_CITY" value="<?php echo $_parametros['MERCHANT_CITY']; ?>">
	<input type="hidden" name="FORWARD_PATH" value="<?php echo $_parametros['FORWARD_PATH']; ?>">
	<input type="hidden" name="3D_CERTIFICATION" value="<?php echo $_parametros['3D_CERTIFICATION']; ?>">
	<input type="hidden" name="REFERENCE3D" value="<?php echo $_parametros['REFERENCE3D']; ?>">
	<input type="hidden" name="CITY" value="<?php echo $_parametros['CITY']; ?>">
	<input type="hidden" name="COUNTRY" value="<?php echo $_parametros['COUNTRY']; ?>">
	<input type="hidden" name="EMAIL" value="<?php echo $_parametros['EMAIL']; ?>">
	<input type="hidden" name="NAME" value="<?php echo $_parametros['NAME']; ?>">
	<input type="hidden" name="LAST_NAME" value="<?php echo $_parametros['LAST_NAME']; ?>">
	<input type="hidden" name="POSTAL_CODE" value="<?php echo $_parametros['POSTAL_CODE']; ?>">
	<input type="hidden" name="STATE" value="<?php echo $_parametros['STATE']; ?>">
	<input type="hidden" name="STREET" value="<?php echo $_parametros['STREET']; ?>">
	<input type="hidden" name="THREED_VERSION" value="<?php echo $_parametros['THREED_VERSION']; ?>">
	<input type="hidden" name="MOBILE_PHONE" value="<?php echo $_parametros['MOBILE_PHONE']; ?>">
	<input type="hidden" name="CREDIT_TYPE" value="<?php echo $_parametros['CREDIT_TYPE']; ?>">
</form>
<script type="text/javascript">
document.payworks_3dsecure.submit();
</script>